### ISSUE TITLE
Rev Squad still autorecalls.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12534]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
That was supposed to be removed a couple days ago.

**Comment by Exxion** [comment]
@gbasood 

Actually, might as well do this, too

**Comment by FudgePucker** [comment]
Rev squad should be fixed.
1) Allow some form of communication between the rev members.
2) Start banning people for not being team players. If a nuke op fucks off into space instead of helping his team he would be banned from being a team based antag. Why is it that no one is being banned for spending the entire round doing nothing to help the team in a round where you can't call the shuttle?

**Comment by icantthinkofanameritenow** [comment]
And by fixed you mean "removed", right? It's objectively worse than revolution in every conceivable way.

**Comment by gbasood** [comment]
If you only want rev to be greytide yeah it is worse
@FudgePucker 1. wyci
2. when you convince admins to ban people for not being good antags

**Comment by gbasood** [comment]
@Exxion yeah i dont have time to figure out why my change for this doesnt work, go ahead
if its still not fixed in mid december nag me I'll take naother look

**Comment by gbasood** [comment]
fff
mention me on discord on the 27th or 28th and link this bug and I'll take YET ANOTHER LOOK AT IT
