### ISSUE TITLE
Rounds end prematurely after statistics get written to file

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#17108]
#### Description of issue
I've experienced this over a few rounds in a row now.
After the round ends and starts counting to a restart, this happens:
![image](https://user-images.githubusercontent.com/5942183/34997832-c6b878dc-fadd-11e7-89a9-cc9b9a9a9ba7.png)

Some seconds later, this happens:
![image](https://user-images.githubusercontent.com/5942183/34997852-d5ccd732-fadd-11e7-9349-183a9020785d.png)
Then the map vote starts.
Then, before the vote actually ends, it stores stuff and ends the round:
![image](https://user-images.githubusercontent.com/5942183/34998011-37ccb84e-fade-11e7-8d64-a9e6e6300aab.png)

I *assume* (partially from having seen crystal delamination rounds in which the restart is 30 seconds, not 60) this happens because the map vote is delayed until statistics have been written to file. If the map vote lasts 60 seconds and the restart happens 60 seconds from roundstart, pushing the map vote back by even just a few seconds will ruin all that.

#### Difference between expected and actual behavior
Rounds are stuck on one map forever unless an admin delays roundend instead of the map vote going through before restart

#### Steps to reproduce 
End round
Don't delay

#### Length of time in which bug has been known to occur

I've only started seeing it recently. Last couple of days, maybe. Probably coincides with the stats being wiped.

#### Server revision

f03b1c69b7a63a23c837bb73cd16a3f2f9910689 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched "round" "vote" "map" "statistics"

**Comment by gbasood** [comment]
Might be fixed with Damian's hotfix

**Comment by Kammerjunk** [comment]
Yeah, probably fixed by #17103
Please wait with closing until a round ends in which this change has been in effect and all (unless you're sure) thanks

**Comment by Kammerjunk** [comment]
I went to bed instead of testing it but I'm assuming from #server-status in the Discord reporting different maps that it actually fixed it

**Comment by DamianX** [comment]
I wouldn't be so sure

**Comment by Kammerjunk** [comment]
Dammit

**Comment by gbasood** [comment]
Still happens, yeah.
The vote timer seems to start up before stats are finished writing, too, so it can shorten or bypass the voting window.

**Comment by DamianX** [comment]
Fixed by #17131
