### ISSUE TITLE
Let's catch up to other servers and let HoP's free job slots.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17843]
1.  Free-job-slot verb already exists for admins.  Getting it to players would involve some NanoUI adjusting and replicating the proc.  It can be given sanity by sending an approval request to Centcomm with a timeout to approve if no one responds and a cooldown timer for the same job so it can't be spammed.
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/admin/admin_verbs.dm#L869

2.  Add a new proc to modify the total_positions variable for a job if a player spends X money to do so.
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/jobs/job/job.dm#L18
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/jobs/job/captain.dm#L6

This is an important feature request because it chips away at the mentality that our codebase is outdated by giving us stuff that other servers have had for a while.

**Comment by jknpj** [comment]
>This is an important feature request because it chips away at the mentality that our codebase is outdated by giving us stuff that other servers have had for a while.

WE'RE NOT BAY

**Comment by Aurx** [comment]
GO BACK TO TG, INTI

**Comment by ghost** [comment]
Eh, as nice as it sounds, I could do without jokesters making 100 clown slots all the time then clowns griefing cause >clown haha grief is cool, admins doing nothing cause >clown haha grief is cool, getting punished by admins cause >haha grief is cool you have to take it or play along up the ladder bitch or it's a ban and being worsened by auto-approve for nomin time. Just one of those we can't have nice things cause people are terrible.

**Comment by Probe1** [comment]
Hence the cost to raise total slots.  Your issue is easily addressed by making the paywall something people find agreeable.

**Comment by jknpj** [comment]
Cult? TIME TO SET CHAPLAIN PRIORITY TO MAXIMUM

**Comment by ghost** [comment]
Money's useless. HoP is best positioned to embezzle basically all the money. even if you make it 5k a job slot, they've already won without even needing to rob the miners or mine themselves.

It's something like 37k before you start stripping people ~250 credits a pop and the salary payments.

**Comment by Probe1** [comment]
We can have nice things without being permanently hindered by any past, present, or future issues with money generation.  If we never touched any code that didn't have issues we'd get no new features at all. And that's the heart of this issue.  Here we are arguing over whether we should have a bog standard feature from 2014 in 2018.

**Comment by ghost** [comment]
Yeah, I know, I'm saying that if the solution to spammed clown slots causing grief is well they cost money, it isn't fixed and probably can't be fixed as long as admins make you climb up the escalation ladder even against blatant grief by a non-antagonist. As long as clowns get so much protection from being preempted I think this is a bad idea leaving it up to whatever admin's lolopinion that you should be griefed for a half hour plus as you climb that ladder with no admin help, potentially validly killed and removed from the round if you respond in any capacity against a fucking griefer without an admin punishment being passed on the clown, or yourself being banned for gibbering a clown who's going out of their way to grief you as soon as they start their shit just so you're left the fuck alone from a nonantagonist violating the rules of the server when the admins don't do shit.

Who knows, the vote will probably put it in but with culture where it is it's playing with fire.

**Comment by Accipitermaris** [comment]
if the issue is just clowns then lets just lock clowns and mimes so you cant request more of those without sanding a fax or w/e like you have to now

i dont think freeing job slots should cost any money though because its a pretty normal administrative action for the hop and unlike generating a new bank account for diona mcgolem doesnt seem like it has an universe reason

it'd sorta be like if calling an ERT costed money (alright thatd be pretty funny actually but you get the idea)

**Comment by SonixApache** [comment]
Being able to retire a crewmember and replace his slot with a new open slot'd be nice.

**Comment by ghost** [comment]
Yeah, it'd get more use out of medhuds/med records by others than me marking people off as people MI failure and the hop can go off that to yoink it. Maybe even prompt a smidge more oversight from the hop bothering the heads, cmo specifically and AI to keep tabs on people here and there so he can free things up. Would be neat long as clown is locked.

Obligatory, wake me up [can't wake up] 
![hello is this the repopulation shuttle](https://user-images.githubusercontent.com/5564796/37432163-4d723856-278c-11e8-880e-c27b410f9a8c.png)

**Comment by Aurx** [comment]
If spam is a worry, could make it require the crewman's ID (or at least an ID with their account number) to "fire" them and mark their spot open.

**Comment by ghost** [comment]
Hmm, I'm not seeing that making a difference. You can't require their physical ID because they're dead in space or otherwise too hazardous to recover/gibbed and the ID with it/murdered and the perp has it. Without that unique req and only an ID with an account number, the hop can still spam whatever even if it's just immediately "firing" whoever joins to keep an infinite amount of "open" slots for that job even if it's one at a time despite using "refund" of existing slots to prevent shit 12 CMO's. If it's made so that the "firing" blanks the access of the existing linked ID(s) it's both a griff tool and still not deterring spam since ID's only matter for a couple things and could simply be restored as a custom id rather than [position] proper. Making it check for slots based on who has x access flags would be a nightmare as things are.

But then, what's the problem with spam. The ones that need to be restricted are clown due to the >I-I'm a proper clown it's okay to griff now, and chaplain due to cult/vampire round interactions. Quartermaster does have a bad interaction due to both having the account pin but is there enough issues from that to be worth a lock? Beyond that, there's little difference from automating the job change at hops/id in comp and getting a screen and loyalty implant if applicable.

**Comment by Riekland** [comment]
the ability to choose a catbeast at roundstart is a 2014 era feature that we STILL don't have

how did we get so behind?

**Comment by Probe1** [comment]
Look at this non admin pleb 
![image](https://user-images.githubusercontent.com/8550416/37442618-c58e7f24-27dd-11e8-95aa-a55e534a9ab6.png)

(admins who play as non standard races roundstart are shitty.

**Comment by Megamaw** [comment]
i don't see there being a huge issue with there being a raised limit on clowns if the HOP designates it so.

i don't agree that the reason is 'because everyone else has it means we should have it'. i think, however, it's a feature that promotes healthier rounds.

after a certain point, only assistants, and the occasional botanist can join the round. this severely limits rounds going on for more than say, an hour or two. latejoining sucks eggs at that point. if someone dies, chances are no one's replacing them.

and please remember that just because he lets there be 10 clowns doesn't mean there's gonna be 10 clowns. there has to be someone that consciously decides to join as a clown. this isn't as wacky and awful as you think.

if the HoP succeeds in his wacky clown plan, though, the captain can always demote him. it's not like we should hold back on adding new content/features because 'b-b-but what if someone ABUSES it?'

**Comment by ghost** [comment]
The hop also being a griefing faggot doesn't make it a good idea for everyone else that gets victimized by it. Nonantag murder and griefing is still banned despite being able to be handled IC. Just because they can doesn't mean people should have to be derailed by and/or devoting time to putting down a bunch of non-antag assholes who solely joined to shit things up with no redeeming value whatsoever cause haha clown grief is "funny". And there's no buts about it. Any week gives plenty of evidence on why clowns are a bad idea. Don't even start on gaping holes in core roles but there's a clown.

Clowns can remain locked for obvious reasons, chaplain can remain locked for cult/vamp reasons, and everyone else can get on with life.

The shrinking manifest doesn't "Severely" limit shit. The vast majority of the time someone can diddle your ID and worst case, there's plenty of ID's to salvage and you can simply settle down with your waifu Emitter to be whatever you wanted to be in many cases. The trivialness of that is also why it's a healthy change.

**Comment by MiniMeatwad** [comment]
this server should have this
