### ISSUE TITLE
Say code issues

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#2644]
Duny told me to make a list of issues that have sprung up since saycode got changed.

It seems as though one of the three clothing venders in the laundry room doesn't work. The first round I noticed it, it was the shoe vender, the next round, it was the hat vender.
Chem dispensers that are built with flatpacks or spawned by admins don't work, the menu doesn't even show up. Just tested and found out that chem dispensers built the normal way don't work either
The 'Universal Understand' variables are missing, which means monkeys can never understand what humans are saying and vice versa
Mice can understand and be understood by humans
Vox raiders cannot talk to the crew or hear them at all, this includes cyborgs.
Flashbangs work on the AI, mommis, and cyborgs now, as in they deafen them
Cyborgs cannot speak on department radio channels, sort of? Apparently they can't hear normal chat when they use it
Mommis cannot speak when outside of keeper mode
This: https://github.com/d3athrow/vgstation13/issues/2641
Vampires cannot suck blood at all
Supply radio channel is black
Msay is still darker than it used to be and it tickles my autism

There's a lot more that I can't remember off the top of my head, and I'm sure we'll see more spring up in the future.

**Comment by d3athrow** [comment]
>It seems as though one of the three clothing venders in the laundry room doesn't work. The first round I noticed it, it was the shoe vender, the next round, it was the hat vender.

Ok

>Chem dispensers that are built with flatpacks or spawned by admins don't work, the menu doesn't even show up. Just tested and found out that chem dispensers built the normal way don't work either

What does this have to do with saycode
>The 'Universal Understand' variables are missing, which means monkeys can never understand what humans are saying and vice versa

Monkeys shouldn't understand humans and vice versa, set their language to 1024 if you want them to though.

>Mice can understand and be understood by humans

Was fixed a few days ago

>Vox raiders cannot talk to the crew or hear them at all, this includes cyborgs.

They should spawn with the human language

>Flashbangs work on the AI, mommis, and cyborgs now, as in they deafen them

OK

>Cyborgs cannot speak on department radio channels, sort of? Apparently they can't hear normal chat when they use it

This was supposedly fixed

>Mommis cannot speak when outside of keeper mode

Riri said he fixed it

>This: #2641

This isn't saycode related.


>Vampires cannot suck blood at all

not say code

>Supply radio channel is black

Was fixed


>Msay is still darker than it used to be and it tickles my autism

Not saycode, but similar.

**Comment by NigglyWiggly** [comment]
>What does this have to do with saycode
>issues that have sprung up since saycode got changed.
I don't know how the fuck they relate to say code, but they only started showing up after it got changed

**Comment by d3athrow** [comment]
Yeah need 2 line breaks after the \> but yeah, most of this popped up from stupid machinery change.

**Comment by NigglyWiggly** [comment]
Oh, my bad. I didn't realize there was a change to machines.

I can confirm that Vox raiders cannot hear or be heard by humans or borgs, I was just a vox raider last round and there was absolutely no communication possible, the only indication that a human/borg had talked was the sprite next to their head, not sure if they could see emotes or not

**Comment by AutismSpider** [comment]
Riri fix lot of things 

not really!

Mommi keeper flag  needs to be tested. (to see if it was really fix and that's round start thing/some admin has to set up dicking with mommi flags and laws set befor the round starts)

With the TG hud pic happens when stacking metal and glass (this happens with engiborg too not just the mommi)
![text error i hope](https://cloud.githubusercontent.com/assets/10268342/5914067/1ab105e4-a5b4-11e4-8ab1-94d01cc59c81.PNG)

Jet-pack bugs out for both cyborgs (engiborg and miner borg) and mommis got use panel to pick the jet-pack then and only then does it work with the TG hud.

Not sure if the mommi stun arm was fix yet never got to test that yet.

**Comment by clusterfack** [comment]
The stun arm thing was one of the earliest things fixed. But it's true the cyborg jetpack problem needs to be addressed. 

I'm not sure whats wrong with the image you posted though, is it saying you cant and ALSO giving them or what?

**Comment by AutismSpider** [comment]
Bit of both saying i can't make it but gives me the stack of PlasmaRglass any way on top of it stacking with normalRglass this happens with normal glass and plasma glass

**Comment by clusterfack** [comment]
The stacking of glass/rglass should be fixed as of yesterday

**Comment by IratePirate** [comment]
Another major issue is that dead people can freely whisper. The implications are staggering.

**Comment by GalaxyGryphon** [comment]
![adsad](https://cloud.githubusercontent.com/assets/10737750/5962942/a27ae0f0-a7b5-11e4-8bff-ab67f6d33aa5.PNG)

**Comment by d3athrow** [comment]
Going to close this, can you seperate still existing issues into their own report?
