### ISSUE TITLE
PA console sprite issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8017]
the Particle Accelerator Control Computer appears at the start of the shift with the wrong sprite (as active); if you wrench it, it will be shown with the right sprite (as inactive)

![particle accelerator control computer](https://cloud.githubusercontent.com/assets/6170726/12726986/ed25f3a6-c91a-11e5-894e-635236a76d91.png)

i saw it on boxstation, i can assume it's the same on all the stations.

**Comment by Intigracy** [comment]
I'm pretty sure this is fixed.

**Comment by clusterfack** [comment]
Doesn't look like it to me

**Comment by Intigracy** [comment]
easy fix, will do tomorrow

**Comment by uazuaz** [comment]
@Intigracy 
still the same. i tried to delete the cache too.

![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/13908499/d88ee31c-ef03-11e5-9784-96ff0ff19cd7.jpg)

**Comment by Intigracy** [comment]
wtf

**Comment by uazuaz** [comment]
@Intigracy 
it seems that it isn't fixed yet.

sorry.

**Comment by ihadtoregisterforthis** [comment]
@uazuaz The fix hasn't been applied yet

**Comment by uazuaz** [comment]
ah ok
