### ISSUE TITLE
Cloning Issue (Monkeyism)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8102]
(WEB REPORT BY: vonzippenstein REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9cb2cff81bce122c4596573433b45605e3d5e52e
> 
> General description of the issue
> Go in clone pod as a human and come out as a monkey.
> 
> Steps to reproduce if possible
> Take a monkey and copy his SE. Inject his SE into a crew member. Inject a clean SE to re-humanize the monkey. Kill the human and clone it. It comes out a monkey.

This seems to happen independant of the information saved on the cloning machine. One round I had saved my DNA at round start. I monkey'd and humanized myself some time later. And when I died someone cloned me from the backup at the cloning machine and I still came out a monkey.

Lately when I monkey around I try to leave a can of methylin to drink and a clean SE around in medbay to overcome the bug.

**Comment by 9600bauds** [comment]
What

**Comment by AutismSpider** [comment]
he came out as a monkey form dna back up some how.

**Comment by 9600bauds** [comment]
Yes, I know

What

**Comment by AutismSpider** [comment]
Old bad code or shit code with how dna back ups work with mobs?

**Comment by Shadowmech88** [comment]
Tested, confirmed this still happens. Interestingly, it *only* happens with backups, not if you clone straight from the corpse.
I can't even begin to imagine what could cause this.

**Comment by Shadowmech88** [comment]
Actually, it may not matter.
Monkeys are completely incapable of being cloned. When scanned, it says "Unable to locate valid genetic data."
As such, this could by fixed by simply forcibly cleaning the last block of any new clone.

**Comment by Shadowmech88** [comment]
I was unable to fix this even in the lazy way. I tried using `SetSEValue()`, `SetSEState()`, `SetSEValueRange()`, I tried putting a `domutcheck()` after, with and without the forced/nofail argument. I even tried delaying the code by a second just in case some kind of race condition-type thing was happening. As far as I can tell I'm doing everything DNA injectors do, and it's not working.
I was never able to turn the monkey back into a human, the most I could manage was a monkey with a deactivated monkey gene, who would not become human until the gene was reactivated in a DNA scanner and then deactivated again.
Save for creating an actual monkey -> human injector item and making it inject the monkey, I think this one is beyond my understanding of Genetics code.

**Comment by Exxion** [comment]
@Kurfursten Sounds like a good contender for the list of hard bugs

**Comment by Exxion** [comment]
What in the unearthly fuck? You get cloned correctly but *then* turn into a monkey
Also for some fucking reason the clone comes out as the appearance you died with rather than the one you were scanned with

**Comment by Exxion** [comment]
OK I still don't know *why* this happened but fixing the second issue also somehow fixed the first
